Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        host: '%env:MYSQL_HOST%'
        dbname: '%env:MYSQL_DATABASE%'
        user: '%env:MYSQL_USER%'
        password: '%env:MYSQL_PASSWORD%'
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: mailhog
        port: 1025

Flowpack:
  ElasticSearch:
    clients:
      default:
        -
          host: elasticsearch
          port: 9200
          username: ''
          password: ''
